AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "lib/generators/trackguard/templates/*.rb"
    - "spec/dummy/**/*"
    - "bin/**/*"
    - "tmp/**/*"

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/SpaceInsideArrayLiteralBrackets:
  EnforcedStyle: space

Metrics/MethodLength:
  Max: 20
  CountAsOne:
    - array
    - hash
    - heredoc

Metrics/AbcSize:
  Max: 30

Metrics/BlockLength:
  Exclude:
    - "spec/**/*.rb"
    - "lib/tasks/**/*.rake"

Metrics/ClassLength:
  Max: 200

Metrics/ModuleLength:
  Max: 200

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/ParameterLists:
  Max: 10

Naming/VariableNumber:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Lint/UnusedMethodArgument:
  AllowUnusedKeywordArguments: true